trigger:
- none
variables:
- name: vmImageName
  value: 'windows-2022' 
stages:
- stage: Build
  displayName: Build
  jobs:
  - job: repro
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzurePowerShell@5
      displayName: 'Generate SQLAccessToken'
      inputs:
        azureSubscription: 'azure_connection'
        azurePowerShellVersion: 'LatestVersion'
        ScriptType: InlineScript
        Inline: |
          $tokenResponse = (Get-AzAccessToken -ResourceUrl https://database.windows.net).Token
          
          if ($tokenResponse) {
            Write-debug "Access token type is $($tokenResponse.token_type), expires $($tokenResponse.expires_on)"
            $Token = $tokenResponse.access_token
          }
          
          write-host "##vso[task.setvariable variable=SPToken]$tokenResponse"

    - task: AzurePowerShell@5
      displayName: 'execute SQL statement'
      inputs:
        azureSubscription: 'azure_connection'
        azurePowerShellVersion: 'LatestVersion'
        ScriptType: InlineScript
        Inline: |
          Invoke-Sqlcmd -ServerInstance $(SQLDatabase) -Database 'AdventureWorksLT' -AccessToken $(SPToken) -query 'SELECT LEFT(SUSER_NAME(),5) as "whoisthis", [name] as "table name" FROM sys.tables;'
